name: Pipeline
on:
  workflow_call:
    
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install GitLeaks
        run: |
          wget -q -O gitleaks.tar.gz https://github.com/gitleaks/gitleaks/releases/download/v8.18.0/gitleaks_8.18.0_linux_x64.tar.gz
          ls -l
          tar -xzvf gitleaks.tar.gz
          chmod +x gitleaks
          sudo mv gitleaks /usr/local/bin/

      - name: Run GitLeaks
        run: |
          gitleaks detect --redact

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Dependency-check
        uses: dependency-check/Dependency-Check_Action@main
        env:
  # actions/setup-java@v1 changes JAVA_HOME so it needs to be reset to match the depcheck image
          JAVA_HOME: /opt/jdk
        id: Depcheck
        with:
          project: 'test'
          path: '.'
          format: 'HTML'
          out: 'reports' # this is the default, no need to specify unless you wish to override it
          args: >
            --failOnCVSS 7
            --enableRetired
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports

      - name: Run Appscan cloud SAST scan
        uses: alphayax/appscan-sast-action@v1
        with:
          api-secret: "Bje41CU/TOW8uNPbGD/ubx7vUQQhe4qnfsUTzvNg1Tvv"
          api-id: "e1ff5c31-c7fc-97ef-7083-db6bb4412bc1"
          application-id: "f80c4c7a-7877-4aa2-8384-9bf4ae293962"
    
